# .goreleaser.yaml
builds:
  # You can have multiple builds defined as a yaml list
  - # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: flagship

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - freebsd
      - windows
      - linux
      - darwin

    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: true

brews:
  - name: flagship
    homepage: "https://github.com/flagship-io/flagship"
    tap:
      owner: flaghsip-io
      name: homebrew-flaghsip
    commit_author:
      name: chadi
      email: chadi.laoulaou@abtasty.com
