name: CI pipeline
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_call:

jobs:
  build:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -race ./... -coverprofile cover.out.tmp -covermode=atomic
      - name: Removes mocks from tests
        run: cat cover.out.tmp | grep -v "_mock.go" > cover.out
      - uses: codecov/codecov-action@v2
        with:
          file: ./cover.out
