name: Release binaries
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF##*/}
      - name: Print env
        run: echo $FLAGSHIP_VERSION
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "FLAGSHIP_VERSION=${{ github.ref_name }}"
          push: true
          tags: chadiii/flagship:${{ steps.vars.outputs.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
